import {proteinResult,activityResult,sleepResult,generalAdult,sourceLinks} from './lifestyle.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=(values,selected)=>values.map(([v,t])=>`<option value="${v}" ${selected===v?'selected':''}>${t}</option>`).join('');
const select=(s,key,label,values)=>`<label class="field">${label}<select id="life-${key}" name="${key}"><option value="">선택해주세요</option>${options(values,s[key])}</select></label>`;
const number=(s,key,label,max,unit)=>`<label class="field">${label}<span class="number-field"><input id="life-${key}" name="${key}" type="number" min="0" max="${max}" step="${key==='proteinGrams'?'0.1':'1'}" inputmode="${key==='proteinGrams'?'decimal':'numeric'}" value="${s[key]??''}" placeholder="0"><span>${unit}</span></span></label>`;
const link=(key,text)=>`<a href="${sourceLinks[key]}" target="_blank" rel="noopener noreferrer">${text} ↗</a>`;
export const lifeQuestions={
  8:['나에게 맞는 참고 기준','나를 위한 기준,<br>조금만 알려줄래요?','식사와 활동을 살펴볼 참고 기준을 고르는 질문이에요.<br>부담스러운 항목은 건너뛰어도 괜찮아요.'],
  9:['하루의 식사','단백질 반찬,<br>하루에 몇 번 챙겨요?','고기·생선·달걀·두부·콩 반찬을 떠올려보세요.<br>배달뿐 아니라 집밥과 간식도 함께요.'],
  10:['하루의 움직임','최근 일주일,<br>몸을 얼마나 움직였나요?','운동 시간은 물론, 숨이 조금 차는 출퇴근길 걷기도요.'],
  11:['하루의 쉼','열심히 보낸 하루,<br>쉬는 시간은 어때요?','최근 일주일의 평소 모습을 골라주세요.'],
};
export function lifestyleQuestion(s,step,choice){
  if(step===8)return `<div class="question-card">${select(s,'age','연령대',[['19-29','19–29세'],['30-49','30–49세'],['50-64','50–64세'],['65+','65세 이상'],['under19','19세 미만'],['skip','기본 정보는 건너뛸게요']])}
  ${s.age&&!['under19','skip'].includes(s.age)?`${select(s,'referenceSex','영양 기준표에서 참고할 성별',[['female','여성 기준'],['male','남성 기준'],['skip','선택하지 않을게요']])}<p class="field-note">2025 한국인 영양소 섭취기준의 연령·성별 참고량을 사용해요. 개인별 필요량과는 차이가 있어요.</p><fieldset class="life-fieldset"><legend>식사·운동에 별도 조절이 필요한가요?</legend><div class="choice-list">${choice('healthContext','general','특별한 조절 없이 생활해요')}${choice('healthContext','personal','개인별 기준을 따르고 있어요','임신·수유, 질환, 치료 등으로 조절이 필요해요')}</div></fieldset>`:''}
  ${s.age==='under19'||s.age==='skip'?'<p class="field-note">성인 기준의 개인 수치 계산은 건너뛰고, 생활 습관 이야기를 이어갈게요.</p>':''}</div><p class="helper">답변은 이 브라우저 탭 안에서만 사용해요.<br>이 테스트는 건강 상태를 진단하지 않아요.</p>`;
  if(step===9)return `<div class="choice-list">${[['rare','자주 빠뜨리는 편이에요','빵·면·밥으로 간단히 끝날 때가 많아요'],['one','하루 한 끼쯤 챙겨요','생각날 때 한 번씩'],['two','하루 두 끼쯤 챙겨요','주요 식사에 곁들이는 편'],['three','매 끼니 챙기는 편이에요','단백질 반찬을 자주 골라요'],['unknown','생각해본 적 없어요','이번에 가볍게 살펴볼래요']].map(x=>choice('proteinHabit',...x)).join('')}</div>
  <fieldset class="life-fieldset"><legend>섭취 기록이 있으면 더 자세하게</legend><div class="compact-choices">${choice('proteinMode','habit','습관으로 알아볼게요')}${choice('proteinMode','record','하루 단백질 g을 알아요')}</div></fieldset>
  ${s.proteinMode==='record'?`<div class="question-card">${number(s,'proteinGrams','기록한 하루의 총 단백질',300,'g')}<p class="field-note">식사 기록 앱·영양표 등으로 확인한 하루 전체 합계를 넣어주세요. 밥·빵·간식·음료의 단백질도 포함해요. 모르면 위의 ‘습관으로 알아볼게요’를 골라주세요.</p></div>`:'<p class="helper">반찬 횟수만으로 부족한 g을 단정하지 않아요.<br>어떤 식품을 챙기면 좋을지 알려드릴게요.</p>'}`;
  if(step===10)return `<div class="choice-list">${[['record','대략 시간을 알고 있어요','최근 7일의 활동 시간을 합해볼게요'],['none','숨이 차는 활동은 거의 없었어요','천천히 걷는 정도예요'],['unknown','잘 모르겠어요','다음 주부터 기록해볼래요'],['limited','통증이나 활동 제한이 있어요','내 몸에 맞는 범위부터 확인할래요']].map(x=>choice('activityMode',...x)).join('')}</div>
  ${s.activityMode==='record'?`<div class="question-card"><p class="card-kicker">최근 7일, 합계 시간</p>${number(s,'moderateMinutes','조금 숨찬 활동 · 빠른 걷기 등',2520,'분 / 주')}${number(s,'vigorousMinutes','많이 숨찬 활동 · 달리기 등',2520,'분 / 주')}<p class="field-note">중강도는 대화는 되지만 노래는 어려운 정도, 고강도는 몇 마디 뒤에 숨을 골라야 하는 정도예요. 하지 않은 활동에는 0을 입력해요. 같은 시간은 한 번만 세어주세요.</p></div>`:''}
  ${['record','none'].includes(s.activityMode)?`${select(s,'strengthDays','근력 운동을 한 날 · 최근 7일',Array.from({length:8},(_,i)=>[i,i===0?'0일 · 하지 않았어요':`${i}일`]))}<p class="field-note">주요 근육을 쓰는 웨이트·맨몸 근력 운동을 한 날이에요. 유산소 시간과 별도로 살펴봐요.</p>`:''}
  ${s.activityMode&&s.activityMode!=='limited'&&generalAdult(s)?`<fieldset class="life-fieldset"><legend>앞으로 해볼 만한 움직임은?</legend><div class="compact-choices three">${choice('exercise','walk','빠른 걷기')}${choice('exercise','bike','자전거')}${choice('exercise','dance','춤추기')}</div></fieldset>${select(s,'planDays','내 생활에 맞는 실천 일수',[[3,'일주일에 3일'],[5,'일주일에 5일'],[7,'일주일에 7일']])}`:''}`;
  return `<fieldset class="life-fieldset first"><legend>하루에 보통 얼마나 자나요?</legend><div class="choice-list">${[['under6','6시간 미만','잠이 짧은 날이 많아요'],['6to7','6시간 이상 ~ 7시간 미만','조금 더 자고 싶어요'],['7to9','7~9시간','이 정도 자는 편이에요'],['over9','9시간보다 길게','충분히 누워 있는 편이에요'],['irregular','그날그날 많이 달라요','일정에 따라 수면도 들쭉날쭉'],['unknown','잘 모르겠어요','시간을 재본 적은 없어요']].map(x=>choice('sleep',...x)).join('')}</div></fieldset><fieldset class="life-fieldset"><legend>자는 시간을 빼고, 앉아 있는 시간은?</legend><div class="compact-choices">${[['under4','4시간 미만'],['4to8','4~8시간 미만'],['over8','8시간 이상'],['unknown','잘 모르겠어요']].map(x=>choice('sitting',...x)).join('')}</div></fieldset>`;
}
export function lifestyleSections(s){
  const p=proteinResult(s),a=activityResult(s),r=sleepResult(s);
  const actions=[{id:'food',icon:'🥣',label:'먹는 일',text:p.action},{id:'move',icon:'👟',label:'움직이는 일',text:a.action},{id:'rest',icon:'🌙',label:'쉬는 일',text:r.action}];
  const special=s.healthContext==='personal'||s.age==='under19';
  const activityFallback=s.activityMode==='limited'||s.healthContext==='personal'?'통증·활동 제한이나 별도 조절이 필요하다고 답했어요. 운동 시간을 자동으로 권하지 않고, 자신의 상태에 맞는 활동을 전문가와 정하도록 안내해요.':s.age==='under19'?'성인 기준의 시간 계산은 건너뛰었어요. 연령에 맞는 활동 기준으로 살펴보고, 좋아하는 움직임을 찾아보세요.':'기본 정보를 건너뛰어 성인 기준의 시간 계산은 하지 않았어요. 이번 주에 움직인 시간을 가볍게 기록해보세요.';
  return `<section class="result-section routine-section" id="routine"><p class="section-number">01 · 나를 챙기는 생활 메모</p><h2>내일은 이 세 가지부터.<br>할 수 있는 것에 체크해봐요.</h2><p class="section-description">전부 바꾸지 않아도 괜찮아요. 하나씩, 내 속도로요.</p><div class="routine-list">${actions.map(x=>`<label class="routine-item"><input id="habit-${x.id}" type="checkbox" name="habitDone" value="${x.id}" ${s.habitsDone.includes(x.id)?'checked':''}><span class="routine-icon" aria-hidden="true">${x.icon}</span><span><small>${x.label}</small><strong>${esc(x.text)}</strong></span><span class="routine-check" aria-hidden="true">✓</span></label>`).join('')}</div><p class="routine-count" aria-live="polite">${s.habitsDone.length?`내가 고른 작은 약속 ${s.habitsDone.length}개`:'부담 없는 약속을 하나 골라보세요'}</p><nav class="result-jumps" aria-label="생활 결과 자세히 보기"><a href="#protein-result">식사 더 보기 ↓</a><a href="#activity-result">활동 더 보기 ↓</a><a href="#sleep-result">수면 더 보기 ↓</a></nav></section>
  <section class="result-section" id="protein-result"><p class="section-number">02 · 내 밥상 채우기</p><h2>${p.gap===null?'단백질, 얼마나보다<br>무엇을 먹는지부터.':p.gap>0?`기록한 하루는 참고량보다<br><em>${p.gap}g</em> 적었어요.`:'기록한 하루는<br>단백질 참고량을 채웠어요.'}</h2>
  ${p.gap!==null?`<div class="life-metric pink"><div><span>입력한 하루 총량</span><strong>${p.intake}<small>g</small></strong></div><span class="metric-divider" aria-hidden="true">/</span><div><span>연령·성별 권장량</span><strong>${p.target}<small>g / 일</small></strong></div></div><div class="life-meter" role="img" aria-label="입력한 단백질 ${p.intake}g, 참고량 ${p.target}g"><span style="width:${Math.min(100,p.intake/p.target*100)}%"></span></div><p class="comparison-note">하루 기록과 일반 권장량의 차이예요. 평소의 단백질 결핍을 뜻하지 않으며, 체격·활동·건강 상태에 따라 필요량은 달라요.</p>`:`<p class="section-description">${special?'개인 수치 계산 대신 식사 습관을 살펴봐요. 연령이나 건강 상태에 맞는 별도 기준이 필요할 수 있어요.':p.target===null?'고른 식사 습관에 맞춘 제안이에요. 하루 전체 섭취량을 몰라 부족한 g은 계산하지 않았어요.':`이 연령·성별의 권장섭취량은 하루 ${p.target}g이에요. 하루 총 섭취량을 몰라 부족한 g은 계산하지 않았어요.`}</p>`}
  <div class="action-note"><span>다음 한 끼의 작은 변화</span><strong>${p.action}</strong></div>
  ${!special?`<div class="protein-foods"><div><span aria-hidden="true">🥛</span><b>우유 200ml</b><small>단백질 약 7g</small></div><div><span aria-hidden="true">🥣</span><b>그릭요거트 100g</b><small>단백질 약 10g</small></div><div><span aria-hidden="true">🍗</span><b>구운 닭가슴살 50g</b><small>단백질 약 16g</small></div></div><p class="comparison-note">식품 예시 중 내 식사와 알레르기 조건에 맞는 것을 골라요. 모두 추가하라는 뜻은 아니에요. 제품·조리법마다 달라 실제 영양표를 확인해요. 두부·콩 반찬으로 바꿔도 좋아요.</p>`:''}
  <button class="button-secondary optional-detail" data-action="life-detail" data-kind="protein">선택 · 단백질 기록으로 더 자세히</button><details class="inline-evidence"><summary>단백질 계산 기준 보기</summary><p>2025 한국인 영양소 섭취기준의 권장섭취량과 사용자가 입력한 하루 전체 섭취량을 비교합니다. 반찬 횟수·좋아하는 배달 메뉴는 섭취량 계산에 쓰지 않습니다. 개인별 섭취 목표를 처방하거나 결핍을 진단하는 결과가 아닙니다.</p>${link('protein','한국인 영양소 섭취기준 · 요약표 xiii')}${link('foods','식품별 단백질 예시')}</details></section>
  <section class="result-section" id="activity-result"><p class="section-number">03 · 내 하루 움직이기</p><h2>${a.quick?esc(a.quick.title):!a.eligible?'내 몸에 맞는<br>움직임부터 찾아봐요.':a.gap===null?'움직인 시간을 알면<br>작은 목표가 보여요.':a.gap===0?'유산소 활동은<br>주간 최소 권장량을 채웠어요.':a.gradual?`하루 ${a.start}분,<br>${a.exercise.name}부터.`:`주 ${a.days}일, 하루 ${a.daily}분<br>${a.exercise.name}를 더해요.`}</h2>
  ${a.gap!==null?`<div class="life-metric green"><div><span>현재 · 중강도 환산</span><strong>${a.equivalent}<small>분 / 주</small></strong></div><span class="metric-divider" aria-hidden="true">→</span><div><span>최소 권장량까지</span><strong>${a.gap}<small>분 남음</small></strong></div></div><p class="comparison-note">중강도 ${s.activityMode==='none'?0:s.moderateMinutes}분 + 고강도 ${s.activityMode==='none'?0:s.vigorousMinutes}분 × 2. 성인 유산소 활동의 최소 권장량인 주 150분과 비교했어요.</p>${a.gap>0?`<div class="action-note green"><span>${a.gradual?'익숙해지면 늘려갈 목표':'기존 활동에 더하는 실천안'}</span><strong>주 ${a.days}일 × 하루 ${a.daily}분 ${a.exercise.name}</strong><p>${a.exercise.cue}. ${a.gradual?`처음엔 하루 ${a.start}분부터 시작하고 천천히 늘려요. 시작 단계에서는 주 150분에 미치지 않을 수 있어요.`:'길게 한 번 하기 어렵다면 하루 안에서 나눠 움직여도 좋아요.'}</p></div>`:''}`:`<p class="section-description">${a.quick?esc(a.quick.description):!a.eligible?activityFallback:'활동량을 모르면 부족한 시간도 계산하지 않아요. 이번 주에는 빠르게 걸은 시간부터 기록해보세요.'}</p>`}
  ${a.eligible?`<p class="body-note">빠른 걷기·자전거·춤은 <b>대화는 되지만 노래는 어려운 정도</b>의 강도로 생각해요. 무리하지 않고 조금씩 늘려요.</p>${a.strengthGap!==null?`<div class="mini-insight"><b>근력 운동은 ${s.strengthDays}일 했어요</b><p>${a.strengthGap?`주 2일 기준까지 ${a.strengthGap}일 더. 주요 근육을 쓰는 맨몸·저항 운동을 가능한 날에 더해보세요.`:'주 2일 이상이라는 빈도 기준을 채웠어요. 주요 근육을 골고루 쓰는지도 살펴보세요.'}</p></div>`:''}${s.age==='65+'?'<p class="body-note">65세 이상은 균형을 기르는 활동도 함께 챙겨요. 개인의 기능과 건강 상태에 맞게 조절하세요.</p>':''}`:''}
  <button class="button-secondary optional-detail" data-action="life-detail" data-kind="activity">선택 · 활동 기록으로 더 자세히</button><details class="inline-evidence"><summary>활동 시간 계산 기준 보기</summary><p>일반 성인 기준은 중강도 유산소 주 150~300분 또는 고강도 75~150분, 근력 활동 주 2일 이상입니다. 이 화면은 유산소의 최소값 150분을 사용합니다. 정확한 기록이 있으면 남은 시간을 주 5일에 나누어 5분 단위로 올림한 예시를 보여줍니다. 실천 일수와 초반 10분 제안은 생활에 맞춘 시작 예시입니다.</p>${link('activity','성인 신체활동 권장 기준')}${link('intensity','운동 강도 구분')}</details></section>
  <section class="result-section" id="sleep-result"><p class="section-number">04 · 내 하루 쉬어가기</p><h2>${r.short?'한 끼만큼 소중한,<br>푹 쉬는 시간.':r.irregular?'하루의 끝에도<br>나만의 리듬을.':'잘 쉬는 것도<br>나를 챙기는 일이니까.'}</h2><p class="section-description">${r.description}</p><div class="action-note lavender"><span>오늘 밤의 작은 약속</span><strong>${r.action}</strong></div>${s.sitting==='over8'||s.sitting==='4to8'?'<div class="mini-insight"><b>오래 앉아 있는 하루라면</b><p>통화할 때, 물 마시러 갈 때처럼 자연스러운 틈에 앉아 있는 시간을 끊어보세요. 스트레칭 시간을 유산소 운동으로 계산하지는 않아요.</p></div>':''}<p class="comparison-note">${generalAdult(s)?'성인 수면 참고: 18~60세 7시간 이상, 61~64세 7~9시간, 65세 이상 7~8시간.':'수면 필요량은 연령과 개인에 따라 달라요.'} ${link('sleep','수면 기준·생활 습관')}</p></section>`;
}
export function lifestyleText(s){const p=proteinResult(s),a=activityResult(s),r=sleepResult(s);return `나를 챙기는 작은 약속\n· ${p.action}\n· ${a.action}\n· ${r.action}\n\n${p.gap!==null?`단백질: 입력한 하루 ${p.intake}g / 연령·성별 참고량 ${p.target}g / 차이 ${p.gap}g\n`:''}${a.gap!==null?`유산소: 중강도 환산 ${a.equivalent}분/주 / 최소 권장량 150분까지 ${a.gap}분\n`:''}하루 기록과 일반 기준의 비교이며 건강 진단이 아닙니다.\n기준: ${sourceLinks.protein}\n${sourceLinks.activity}\n${sourceLinks.sleep}`;}
